// <auto-generated />
using System;
using BigSchool.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigSchool.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BigSchoolDbContext))]
    partial class BigSchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BigSchool.Domain.Entities.SubCategory", b =>
                {
                    b.Property<int>("IdSubCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSubCategory"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdMainCategory")
                        .HasColumnType("int");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdSubCategory");

                    b.HasIndex("IdUser");

                    b.ToTable("SubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            IdSubCategory = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Supermercado"
                        },
                        new
                        {
                            IdSubCategory = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Farmacia"
                        },
                        new
                        {
                            IdSubCategory = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Facturas"
                        },
                        new
                        {
                            IdSubCategory = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Seguros"
                        },
                        new
                        {
                            IdSubCategory = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Transporte"
                        },
                        new
                        {
                            IdSubCategory = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 2,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Bolsa"
                        },
                        new
                        {
                            IdSubCategory = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 2,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Fondos"
                        },
                        new
                        {
                            IdSubCategory = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 2,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Crypto"
                        },
                        new
                        {
                            IdSubCategory = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 3,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Cuenta ahorro"
                        },
                        new
                        {
                            IdSubCategory = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 3,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Depósitos"
                        },
                        new
                        {
                            IdSubCategory = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Restaurantes"
                        },
                        new
                        {
                            IdSubCategory = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Ocio"
                        },
                        new
                        {
                            IdSubCategory = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Viajes"
                        },
                        new
                        {
                            IdSubCategory = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Ropa"
                        },
                        new
                        {
                            IdSubCategory = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Tecnología"
                        },
                        new
                        {
                            IdSubCategory = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 6,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Cursos"
                        },
                        new
                        {
                            IdSubCategory = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 6,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Libros"
                        },
                        new
                        {
                            IdSubCategory = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 6,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Máster"
                        },
                        new
                        {
                            IdSubCategory = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 4,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "ONG"
                        },
                        new
                        {
                            IdSubCategory = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 7,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Hipoteca"
                        },
                        new
                        {
                            IdSubCategory = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 7,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Préstamo"
                        },
                        new
                        {
                            IdSubCategory = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 10,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Empresa principal"
                        },
                        new
                        {
                            IdSubCategory = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 11,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Vivienda"
                        },
                        new
                        {
                            IdSubCategory = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 11,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Local"
                        },
                        new
                        {
                            IdSubCategory = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 11,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Garaje"
                        },
                        new
                        {
                            IdSubCategory = 26,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 12,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Acciones nacionales"
                        },
                        new
                        {
                            IdSubCategory = 27,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 12,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Acciones internacionales"
                        },
                        new
                        {
                            IdSubCategory = 28,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 13,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Otros ingresos"
                        });
                });

            modelBuilder.Entity("BigSchool.Domain.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BigSchool.Domain.Entities.SubCategory", b =>
                {
                    b.HasOne("BigSchool.Domain.Entities.User", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BigSchool.Domain.Entities.User", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
