<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" Version="$(MediatRVersion)" />
    <PackageReference Include="AutoMapper" Version="$(AutoMapperVersion)" />
    <PackageReference Include="FluentValidation" Version="$(FluentValidationVersion)" />
    <PackageReference Include="Dapper" Version="$(DapperVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BigSchool.Domain\BigSchool.Domain.csproj" />
  </ItemGroup>

</Project>
