// <auto-generated />
using System;
using BigSchool.Infrastructure.SharedKernel.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigSchool.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BigSchoolDbContext))]
    [Migration("20260704144600_AddNotificationsModule")]
    partial class AddNotificationsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BigSchool.Domain.Auth.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValueSql("'EUR'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BigSchool.Domain.Finanzas.Entities.SubCategory", b =>
                {
                    b.Property<int>("IdSubCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSubCategory"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdMainCategory")
                        .HasColumnType("int");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdSubCategory");

                    b.HasIndex("IdUser");

                    b.ToTable("SubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            IdSubCategory = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Supermercado"
                        },
                        new
                        {
                            IdSubCategory = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Farmacia"
                        },
                        new
                        {
                            IdSubCategory = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Facturas"
                        },
                        new
                        {
                            IdSubCategory = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Seguros"
                        },
                        new
                        {
                            IdSubCategory = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 1,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Transporte"
                        },
                        new
                        {
                            IdSubCategory = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 2,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Bolsa"
                        },
                        new
                        {
                            IdSubCategory = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 2,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Fondos"
                        },
                        new
                        {
                            IdSubCategory = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 2,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Crypto"
                        },
                        new
                        {
                            IdSubCategory = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 3,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Cuenta ahorro"
                        },
                        new
                        {
                            IdSubCategory = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 3,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Depósitos"
                        },
                        new
                        {
                            IdSubCategory = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Restaurantes"
                        },
                        new
                        {
                            IdSubCategory = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Ocio"
                        },
                        new
                        {
                            IdSubCategory = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Viajes"
                        },
                        new
                        {
                            IdSubCategory = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Ropa"
                        },
                        new
                        {
                            IdSubCategory = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 5,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Tecnología"
                        },
                        new
                        {
                            IdSubCategory = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 6,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Cursos"
                        },
                        new
                        {
                            IdSubCategory = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 6,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Libros"
                        },
                        new
                        {
                            IdSubCategory = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 6,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Máster"
                        },
                        new
                        {
                            IdSubCategory = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 4,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "ONG"
                        },
                        new
                        {
                            IdSubCategory = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 7,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Hipoteca"
                        },
                        new
                        {
                            IdSubCategory = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 7,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Préstamo"
                        },
                        new
                        {
                            IdSubCategory = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 10,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Empresa principal"
                        },
                        new
                        {
                            IdSubCategory = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 11,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Vivienda"
                        },
                        new
                        {
                            IdSubCategory = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 11,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Local"
                        },
                        new
                        {
                            IdSubCategory = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 11,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Garaje"
                        },
                        new
                        {
                            IdSubCategory = 26,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 12,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Acciones nacionales"
                        },
                        new
                        {
                            IdSubCategory = 27,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 12,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Acciones internacionales"
                        },
                        new
                        {
                            IdSubCategory = 28,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdMainCategory = 13,
                            IdStatus = (short)2,
                            IsDefault = true,
                            Name = "Otros ingresos"
                        });
                });

            modelBuilder.Entity("BigSchool.Domain.Finanzas.Entities.Transaction", b =>
                {
                    b.Property<int>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTransaction"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdMainCategory")
                        .HasColumnType("int");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<int?>("IdSubCategory")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdTransaction");

                    b.HasIndex("IdSubCategory");

                    b.HasIndex("IdUser", "TransactionDate");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Company", b =>
                {
                    b.Property<int>("IdCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCompany"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValueSql("'EUR'");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<string>("Market")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdCompany");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            IdCompany = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IdStatus = (short)2,
                            Market = "NASDAQ",
                            Name = "Apple Inc.",
                            Sector = "Technology",
                            Ticker = "AAPL"
                        },
                        new
                        {
                            IdCompany = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IdStatus = (short)2,
                            Market = "NASDAQ",
                            Name = "Microsoft Corp.",
                            Sector = "Technology",
                            Ticker = "MSFT"
                        },
                        new
                        {
                            IdCompany = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            IdStatus = (short)2,
                            Market = "BME",
                            Name = "Banco Santander",
                            Sector = "Financials",
                            Ticker = "SAN"
                        },
                        new
                        {
                            IdCompany = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "GBP",
                            IdStatus = (short)2,
                            Market = "LSE",
                            Name = "Shell plc",
                            Sector = "Energy",
                            Ticker = "SHEL"
                        });
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Disposal", b =>
                {
                    b.Property<int>("IdDisposal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDisposal"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdHolding")
                        .HasColumnType("int");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateOnly>("SellDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Shares")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdDisposal");

                    b.HasIndex("IdHolding");

                    b.ToTable("Disposals", (string)null);
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Holding", b =>
                {
                    b.Property<int>("IdHolding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHolding"));

                    b.Property<DateOnly>("BuyDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<int>("IdPortfolio")
                        .HasColumnType("int");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Shares")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdHolding");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdPortfolio", "IdCompany");

                    b.ToTable("Holdings", (string)null);
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Portfolio", b =>
                {
                    b.Property<int>("IdPortfolio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPortfolio"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdPortfolio");

                    b.HasIndex("IdUser");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Valuation", b =>
                {
                    b.Property<int>("IdValuation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdValuation"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdValuation");

                    b.HasIndex("IdCompany", "Date")
                        .IsUnique();

                    b.ToTable("Valuations", (string)null);

                    b.HasData(
                        new
                        {
                            IdValuation = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 2),
                            IdCompany = 1,
                            IdStatus = (short)2,
                            Source = "seed"
                        },
                        new
                        {
                            IdValuation = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 3, 2),
                            IdCompany = 1,
                            IdStatus = (short)2,
                            Source = "seed"
                        },
                        new
                        {
                            IdValuation = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 2),
                            IdCompany = 2,
                            IdStatus = (short)2,
                            Source = "seed"
                        },
                        new
                        {
                            IdValuation = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 3, 2),
                            IdCompany = 2,
                            IdStatus = (short)2,
                            Source = "seed"
                        },
                        new
                        {
                            IdValuation = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 2),
                            IdCompany = 3,
                            IdStatus = (short)2,
                            Source = "seed"
                        },
                        new
                        {
                            IdValuation = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 3, 2),
                            IdCompany = 3,
                            IdStatus = (short)2,
                            Source = "seed"
                        },
                        new
                        {
                            IdValuation = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 2),
                            IdCompany = 4,
                            IdStatus = (short)2,
                            Source = "seed"
                        },
                        new
                        {
                            IdValuation = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 3, 2),
                            IdCompany = 4,
                            IdStatus = (short)2,
                            Source = "seed"
                        });
                });

            modelBuilder.Entity("BigSchool.Domain.Notifications.Entities.Contact", b =>
                {
                    b.Property<int>("IdContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdContact"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("IdContact");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("BigSchool.Domain.Notifications.Entities.EmailLog", b =>
                {
                    b.Property<int>("IdEmailLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmailLog"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2);

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("IdEmailLog");

                    b.HasIndex("IdUser");

                    b.ToTable("EmailLogs", (string)null);
                });

            modelBuilder.Entity("BigSchool.Domain.SharedKernel.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("IdExchangeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdExchangeRate"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.HasKey("IdExchangeRate");

                    b.HasIndex("FromCurrency", "ToCurrency", "RateDate")
                        .IsUnique();

                    b.ToTable("ExchangeRates", (string)null);

                    b.HasData(
                        new
                        {
                            IdExchangeRate = 1,
                            FetchedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FromCurrency = "USD",
                            Rate = 0.920000m,
                            RateDate = new DateOnly(2026, 1, 1),
                            Source = "seed",
                            ToCurrency = "EUR"
                        },
                        new
                        {
                            IdExchangeRate = 2,
                            FetchedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FromCurrency = "GBP",
                            Rate = 1.170000m,
                            RateDate = new DateOnly(2026, 1, 1),
                            Source = "seed",
                            ToCurrency = "EUR"
                        },
                        new
                        {
                            IdExchangeRate = 3,
                            FetchedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FromCurrency = "CHF",
                            Rate = 1.060000m,
                            RateDate = new DateOnly(2026, 1, 1),
                            Source = "seed",
                            ToCurrency = "EUR"
                        },
                        new
                        {
                            IdExchangeRate = 4,
                            FetchedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FromCurrency = "JPY",
                            Rate = 0.006100m,
                            RateDate = new DateOnly(2026, 1, 1),
                            Source = "seed",
                            ToCurrency = "EUR"
                        });
                });

            modelBuilder.Entity("BigSchool.Infrastructure.SharedKernel.IntegrationEvents.OutboxMessage", b =>
                {
                    b.Property<long>("IdOutboxMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdOutboxMessage"));

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("IdOutboxMessage");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("ProcessedOn");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("BigSchool.Domain.Finanzas.Entities.SubCategory", b =>
                {
                    b.HasOne("BigSchool.Domain.Auth.Entities.User", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BigSchool.Domain.Finanzas.Entities.Transaction", b =>
                {
                    b.HasOne("BigSchool.Domain.Finanzas.Entities.SubCategory", null)
                        .WithMany()
                        .HasForeignKey("IdSubCategory")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BigSchool.Domain.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.MoneyConversion", "Conversion", b1 =>
                        {
                            b1.Property<int>("TransactionIdTransaction")
                                .HasColumnType("int");

                            b1.Property<decimal>("Rate")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("ExchangeRate");

                            b1.Property<DateOnly>("RateDate")
                                .HasColumnType("date")
                                .HasColumnName("RateDate");

                            b1.HasKey("TransactionIdTransaction");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionIdTransaction");

                            b1.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.Money", "Base", b2 =>
                                {
                                    b2.Property<int>("MoneyConversionTransactionIdTransaction")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("BaseAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("char(3)")
                                        .HasColumnName("BaseCurrency");

                                    b2.HasKey("MoneyConversionTransactionIdTransaction");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyConversionTransactionIdTransaction");
                                });

                            b1.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.Money", "Original", b2 =>
                                {
                                    b2.Property<int>("MoneyConversionTransactionIdTransaction")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("OriginalAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("char(3)")
                                        .HasColumnName("OriginalCurrency");

                                    b2.HasKey("MoneyConversionTransactionIdTransaction");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyConversionTransactionIdTransaction");
                                });

                            b1.Navigation("Base")
                                .IsRequired();

                            b1.Navigation("Original")
                                .IsRequired();
                        });

                    b.Navigation("Conversion")
                        .IsRequired();
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Disposal", b =>
                {
                    b.HasOne("BigSchool.Domain.Investments.Entities.Holding", null)
                        .WithMany("Disposals")
                        .HasForeignKey("IdHolding")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.Money", "RealizedPnL", b1 =>
                        {
                            b1.Property<int>("DisposalIdDisposal")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("RealizedPnL");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("RealizedPnLCurrency");

                            b1.HasKey("DisposalIdDisposal");

                            b1.ToTable("Disposals");

                            b1.WithOwner()
                                .HasForeignKey("DisposalIdDisposal");
                        });

                    b.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.MoneyConversion", "SellPrice", b1 =>
                        {
                            b1.Property<int>("DisposalIdDisposal")
                                .HasColumnType("int");

                            b1.Property<decimal>("Rate")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("SellExchangeRate");

                            b1.Property<DateOnly>("RateDate")
                                .HasColumnType("date")
                                .HasColumnName("SellRateDate");

                            b1.HasKey("DisposalIdDisposal");

                            b1.ToTable("Disposals");

                            b1.WithOwner()
                                .HasForeignKey("DisposalIdDisposal");

                            b1.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.Money", "Base", b2 =>
                                {
                                    b2.Property<int>("MoneyConversionDisposalIdDisposal")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("SellBaseAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("char(3)")
                                        .HasColumnName("SellBaseCurrency");

                                    b2.HasKey("MoneyConversionDisposalIdDisposal");

                                    b2.ToTable("Disposals");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyConversionDisposalIdDisposal");
                                });

                            b1.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.Money", "Original", b2 =>
                                {
                                    b2.Property<int>("MoneyConversionDisposalIdDisposal")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("SellOriginalAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("char(3)")
                                        .HasColumnName("SellOriginalCurrency");

                                    b2.HasKey("MoneyConversionDisposalIdDisposal");

                                    b2.ToTable("Disposals");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyConversionDisposalIdDisposal");
                                });

                            b1.Navigation("Base")
                                .IsRequired();

                            b1.Navigation("Original")
                                .IsRequired();
                        });

                    b.Navigation("RealizedPnL")
                        .IsRequired();

                    b.Navigation("SellPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Holding", b =>
                {
                    b.HasOne("BigSchool.Domain.Investments.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BigSchool.Domain.Investments.Entities.Portfolio", null)
                        .WithMany("Holdings")
                        .HasForeignKey("IdPortfolio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.MoneyConversion", "AvgBuyPrice", b1 =>
                        {
                            b1.Property<int>("HoldingIdHolding")
                                .HasColumnType("int");

                            b1.Property<decimal>("Rate")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("BuyExchangeRate");

                            b1.Property<DateOnly>("RateDate")
                                .HasColumnType("date")
                                .HasColumnName("BuyRateDate");

                            b1.HasKey("HoldingIdHolding");

                            b1.ToTable("Holdings");

                            b1.WithOwner()
                                .HasForeignKey("HoldingIdHolding");

                            b1.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.Money", "Base", b2 =>
                                {
                                    b2.Property<int>("MoneyConversionHoldingIdHolding")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("BuyBaseAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("char(3)")
                                        .HasColumnName("BuyBaseCurrency");

                                    b2.HasKey("MoneyConversionHoldingIdHolding");

                                    b2.ToTable("Holdings");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyConversionHoldingIdHolding");
                                });

                            b1.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.Money", "Original", b2 =>
                                {
                                    b2.Property<int>("MoneyConversionHoldingIdHolding")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("BuyOriginalAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("char(3)")
                                        .HasColumnName("BuyOriginalCurrency");

                                    b2.HasKey("MoneyConversionHoldingIdHolding");

                                    b2.ToTable("Holdings");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyConversionHoldingIdHolding");
                                });

                            b1.Navigation("Base")
                                .IsRequired();

                            b1.Navigation("Original")
                                .IsRequired();
                        });

                    b.Navigation("AvgBuyPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Portfolio", b =>
                {
                    b.HasOne("BigSchool.Domain.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.Money", "RealizedPnL", b1 =>
                        {
                            b1.Property<int>("PortfolioIdPortfolio")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("RealizedPnL");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("RealizedPnLCurrency");

                            b1.HasKey("PortfolioIdPortfolio");

                            b1.ToTable("Portfolios");

                            b1.WithOwner()
                                .HasForeignKey("PortfolioIdPortfolio");
                        });

                    b.Navigation("RealizedPnL")
                        .IsRequired();
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Valuation", b =>
                {
                    b.HasOne("BigSchool.Domain.Investments.Entities.Company", null)
                        .WithMany("Valuations")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BigSchool.Domain.SharedKernel.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<int>("ValuationIdValuation")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("ValuationIdValuation");

                            b1.ToTable("Valuations");

                            b1.WithOwner()
                                .HasForeignKey("ValuationIdValuation");

                            b1.HasData(
                                new
                                {
                                    ValuationIdValuation = 1,
                                    Amount = 195.0000m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ValuationIdValuation = 2,
                                    Amount = 210.0000m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ValuationIdValuation = 3,
                                    Amount = 420.0000m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ValuationIdValuation = 4,
                                    Amount = 440.0000m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ValuationIdValuation = 5,
                                    Amount = 4.5000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    ValuationIdValuation = 6,
                                    Amount = 4.8000m,
                                    Currency = "EUR"
                                },
                                new
                                {
                                    ValuationIdValuation = 7,
                                    Amount = 28.0000m,
                                    Currency = "GBP"
                                },
                                new
                                {
                                    ValuationIdValuation = 8,
                                    Amount = 30.0000m,
                                    Currency = "GBP"
                                });
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("BigSchool.Domain.Auth.Entities.User", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Company", b =>
                {
                    b.Navigation("Valuations");
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Holding", b =>
                {
                    b.Navigation("Disposals");
                });

            modelBuilder.Entity("BigSchool.Domain.Investments.Entities.Portfolio", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
