<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EFCoreVersion)" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="$(PomeloVersion)" />
    <PackageReference Include="Dapper" Version="$(DapperVersion)" />
    <PackageReference Include="MediatR" Version="$(MediatRVersion)" />
    <PackageReference Include="Isopoh.Cryptography.Argon2" Version="$(Argon2Version)" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="$(OptionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="$(OptionsVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BigSchool.Domain\BigSchool.Domain.csproj" />
    <ProjectReference Include="..\BigSchool.Application\BigSchool.Application.csproj" />
  </ItemGroup>

</Project>
