<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)" />
    <PackageReference Include="xunit" Version="$(xUnitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(XunitRunnerVisualStudioVersion)" />
    <PackageReference Include="FluentAssertions" Version="$(FluentAssertionsVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="$(MvcTestingVersion)" />
    <PackageReference Include="WireMock.Net" Version="$(WireMockVersion)" />
    <PackageReference Include="Dapper" Version="$(DapperVersion)" />
    <PackageReference Include="MySqlConnector" Version="$(MySqlConnectorVersion)" />
    <PackageReference Include="Moq" Version="$(MoqVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BigSchool.WebApi\BigSchool.WebApi.csproj" />
    <ProjectReference Include="..\..\src\BigSchool.Infrastructure\BigSchool.Infrastructure.csproj" />
  </ItemGroup>

</Project>
